[package]
name = "iced_stuff"
version = "0.1.0"
edition = "2024"

[dependencies]
asset_system = { path = "asset_system" }
anyhow = "1.0.99"
iced = { version = "0.13.1", features = [
    "debug",
    "image",
    "canvas",
    "advanced",
    "lazy",
    "async-std",
] }
iced_aw = { version = "0.12.2", features = [
    "context_menu",
    "menu",
    "badge",
    "card",
    "grid",
    "tab_bar",
] }
itertools = "0.14.0"
lyon_algorithms = "1.0.5"
palette = "0.7.6"
rfd = "0.15.4"
ron = "0.11.0"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.16"
